### ISSUE TITLE
Not opening not-empty files

### ISSUE THREAD

**Issue by carzilla** [humy2833/FTP-Simple#180]
Since the last update, the extension cannot ftp-open files that aren't empty. Empty files are no problem. If you open it and save it, it successfully uploads the file. If you then close it in the editor and try to reopen it through ftp-simple: Open, it doesn't open anymore.

**Comment by JomsonStudio** [comment]
Same issue

**Comment by nikolay94** [comment]
Same issue +1

**Comment by KamasamaK** [comment]
Probably duplicate of #177

**Comment by MSDevelops** [comment]
Same issue +1

**Comment by benderlidze** [comment]
Same +1

**Comment by seulbiK** [comment]
Same issue :(

**Comment by humy2833** [comment]
We apologize for any inconvenience.
There was a problem with the internal ftp module that was being used when VSCode version 1.31 was upgraded.
Please use VSCode downgrade (1.30) while correcting the problem.
(Try "type" with "ftp2" instead of "ftp".
"ftp2" will attempt to connect to another module internally. But it may not.)

**Comment by KamasamaK** [comment]
Problem is fixed with v0.7.0

**Comment by hyungjungson** [comment]
same issue

**Comment by antonzolotar** [comment]
same issue and error in "OUTPUT > Journal (Window)":
`[2019-04-18 08:54:04.843] [renderer1] [error] Cannot read property 'host' of null: TypeError: Cannot read property 'host' of null
	at createFTP (C:\Users\BuG\.vscode\extensions\humy2833.ftp-simple-0.7.0\extension.js:930:20)
	at C:\Users\BuG\.vscode\extensions\humy2833.ftp-simple-0.7.0\extension.js:132:7
	at u.fire (c:\Users\BuG\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at define.constructor._extHostDocumentsAndEditors.onDidChangeActiveTextEditor.e (c:\Users\BuG\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:575:305)
	at u.fire (c:\Users\BuG\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at u.$acceptDocumentsAndEditorsDelta (c:\Users\BuG\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:522:159)
	at d._doInvokeHandler (c:\Users\BuG\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:622:11)
	at d._invokeHandler (c:\Users\BuG\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:621:716)
	at d._receiveRequest (c:\Users\BuG\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:620:394)
	at d._receiveOneMessage (c:\Users\BuG\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:619:141)
	at define.constructor._protocol.onMessage.e (c:\Users\BuG\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:617:400)
	at u.fire (c:\Users\BuG\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at e (c:\Users\BuG\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:40:460)
	at u.fire (c:\Users\BuG\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at a (c:\Users\BuG\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:172:467)
	at e (c:\Users\BuG\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:172:513)
	at u.fire (c:\Users\BuG\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at y._receiveMessage (c:\Users\BuG\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:181:276)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (c:\Users\BuG\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:178:415)
	at u.fire (c:\Users\BuG\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at f.acceptChunk (c:\Users\BuG\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:175:35)
	at define.constructor._register._socket.onData.e (c:\Users\BuG\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:174:410)
	at Socket.t (c:\Users\BuG\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:182:689)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)`
